/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { ContentRoute } from "../ContentIndexer";

export const glossary: ContentRoute[] = [
  {
    url: "/glossary/iam",
    title: "Identity and Access Management (IAM) Definition | CyberTeck OS Glossary",
    description: "What is IAM? Explore Identity and Access Management definitions, enterprise applications, and modern multi-factor integrations.",
    category: "glossary",
    keywords: ["IAM", "Identity Governance", "User Directories", "Access Entitlements", "Sovereign Authentication"],
    summary: "Identity and Access Management (IAM) is a framework of policies and technologies for ensuring that the proper people in an enterprise have the appropriate access to technology resources.",
    faqs: [],
    parent: "/resources",
    children: []
  },
  {
    url: "/glossary/pam",
    title: "Privileged Access Management (PAM) Definition | CyberTeck OS Glossary",
    description: "What is PAM? Learn about Privileged Access Management, administrative console security, and dynamic session monitoring.",
    category: "glossary",
    keywords: ["PAM", "Privileged Accounts", "Administrative Access", "Session Recording", "Credential Vaults"],
    summary: "Privileged Access Management (PAM) refers to a class of cybersecurity solutions designed to secure, control, monitor, and audit privileged access to critical assets and infrastructures.",
    faqs: [],
    parent: "/resources",
    children: []
  },
  {
    url: "/glossary/siem",
    title: "Security Information and Event Management (SIEM) | CyberTeck OS Glossary",
    description: "What is SIEM? Learn about Security Information and Event Management, high-volume event ingestion, and real-time alert triage.",
    category: "glossary",
    keywords: ["SIEM", "Log Collection", "Event Aggregation", "Correlation Rules", "Alert Ingestion"],
    summary: "Security Information and Event Management (SIEM) is a subsection of cybersecurity that provides real-time analysis of security alerts generated by applications and network hardware.",
    faqs: [],
    parent: "/resources",
    children: []
  },
  {
    url: "/glossary/soar",
    title: "Security Orchestration, Automation, and Response (SOAR) | CyberTeck OS Glossary",
    description: "What is SOAR? Definition of Security Orchestration, Automation, and Response. Automated playbook deployment and incident response.",
    category: "glossary",
    keywords: ["SOAR", "Playbooks Automation", "Incident Escalation", "Security Integrations", "Container Isolation"],
    summary: "Security Orchestration, Automation, and Response (SOAR) technologies enable companies to collect security data and alerts from different sources, automating standardized incident response playbooks.",
    faqs: [],
    parent: "/resources",
    children: []
  },
  {
    url: "/glossary/cspm",
    title: "Cloud Security Posture Management (CSPM) Definition | CyberTeck OS Glossary",
    description: "What is CSPM? Learn about Cloud Security Posture Management, misconfigured database buckets, and continuous posture checks.",
    category: "glossary",
    keywords: ["CSPM", "Cloud Configuration", "Posture Tracking", "Resource Drifts", "Sovereign Cloud"],
    summary: "Cloud Security Posture Management (CSPM) is an IT security tool class designed to identify misconfiguration and compliance risks in public or sovereign cloud infrastructures.",
    faqs: [],
    parent: "/resources",
    children: []
  },
  {
    url: "/glossary/cwpp",
    title: "Cloud Workload Protection Platform (CWPP) | CyberTeck OS Glossary",
    description: "What is CWPP? Cloud Workload Protection Platform definition. Secure application containers and virtual machine workloads.",
    category: "glossary",
    keywords: ["CWPP", "Container Security", "Workload Hardening", "Runtime Protection", "Serverless Telemetry"],
    summary: "A Cloud Workload Protection Platform (CWPP) is a workload-centric security solution that addresses the unique protection requirements of modern cloud containers, serverless architectures, and virtual machines.",
    faqs: [],
    parent: "/resources",
    children: []
  },
  {
    url: "/glossary/dlp",
    title: "Data Loss Prevention (DLP) Definition | CyberTeck OS Glossary",
    description: "What is DLP? Explore Data Loss Prevention mechanisms, keyword tracking, and automated file classification rules.",
    category: "glossary",
    keywords: ["DLP", "Data Protection", "Information Leaks", "PII Redaction", "Document Classifications"],
    summary: "Data Loss Prevention (DLP) is a program or set of technologies designed to detect and prevent unauthorized transmission or leakage of sensitive corporate information outside organization boundaries.",
    faqs: [],
    parent: "/resources",
    children: []
  },
  {
    url: "/glossary/hsm",
    title: "Hardware Security Module (HSM) Definition | CyberTeck OS Glossary",
    description: "What is HSM? Learn about Hardware Security Modules, cryptographic key generation, and secure tamper-proof storage.",
    category: "glossary",
    keywords: ["HSM", "Cryptographic Hardware", "Key Management", "Physical Tampering", "FIPS 140-2"],
    summary: "A Hardware Security Module (HSM) is a physical, dedicated computing device that safeguards and manages digital keys, performing cryptographic operations for strong authentication and document signatures.",
    faqs: [],
    parent: "/resources",
    children: []
  },
  {
    url: "/glossary/dpdp",
    title: "Digital Personal Data Protection Act (DPDP) | CyberTeck OS Glossary",
    description: "Definition of India's Digital Personal Data Protection Act (2023). Core rules, rights, penalties, and obligations.",
    category: "glossary",
    keywords: ["DPDP Act", "Data Fiduciary", "Data Principal", "Consent Manager", "Personal Data Protection"],
    summary: "The Digital Personal Data Protection Act (2023) is India's principal statutory legislation governing the collection, processing, erasure, and security of digital personal data.",
    faqs: [],
    parent: "/resources",
    children: []
  },
  {
    url: "/glossary/cert-in",
    title: "Indian Computer Emergency Response Team (CERT-In) | CyberTeck OS Glossary",
    description: "What is CERT-In? Learn about the Indian Computer Emergency Response Team, incident notification laws, and reporting thresholds.",
    category: "glossary",
    keywords: ["CERT-In", "Incident Reporting", "Information Technology Act", "6-Hour Rule", "Emergency Response"],
    summary: "The Indian Computer Emergency Response Team (CERT-In) is the national nodal agency under the Ministry of Electronics and Information Technology (MeitY) tasked with responding to cyber security incidents across India.",
    faqs: [],
    parent: "/resources",
    children: []
  },
  {
    url: "/glossary/rbi-framework",
    title: "RBI Cyber Security Framework | CyberTeck OS Glossary",
    description: "Definition of the Reserve Bank of India Cyber Security Guidelines. Requirements for core banking, NBFCs, and financial gateways.",
    category: "glossary",
    keywords: ["RBI Framework", "Banking Cybersecurity", "BFSI Auditing", "Transaction Gateway", "NBFC Controls"],
    summary: "The RBI Cyber Security Framework is a set of comprehensive regulatory guidelines issued by the Reserve Bank of India to govern and standardize the cybersecurity posture of commercial banks and NBFCs.",
    faqs: [],
    parent: "/resources",
    children: []
  },
  {
    url: "/glossary/sebi",
    title: "Securities and Exchange Board of India (SEBI) | CyberTeck OS Glossary",
    description: "What is SEBI? Explore cybersecurity circulars and operational resilience frameworks governing Indian capital markets.",
    category: "glossary",
    keywords: ["SEBI", "Capital Markets", "Brokers Security", "Resilience Mandates", "Stock Exchanges"],
    summary: "The Securities and Exchange Board of India (SEBI) is the regulator for the securities market in India, enforcing specific guidelines on cybersecurity governance, VAPT, and cyber-breach reporting for capital market intermediaries.",
    faqs: [],
    parent: "/resources",
    children: []
  },
  {
    url: "/glossary/fido2",
    title: "FIDO2 Passwordless Authentication | CyberTeck OS Glossary",
    description: "What is FIDO2? Learn about Fast Identity Online passwordless security standard, hardware keys, and phishing resistance.",
    category: "glossary",
    keywords: ["FIDO2", "WebAuthn", "Passwordless Logins", "Phishing Resistance", "Biometric Keys"],
    summary: "FIDO2 is a global passwordless authentication standard created by the FIDO Alliance. It leverages cryptography to enable strong, phishing-resistant logins across web-based applications using hardware keys and platform biometrics.",
    faqs: [],
    parent: "/resources",
    children: []
  },
  {
    url: "/glossary/apt",
    title: "Advanced Persistent Threat (APT) Definition | CyberTeck OS Glossary",
    description: "What is an APT? Definition of Advanced Persistent Threat, state-sponsored cyber espionage, and infiltration pathways.",
    category: "glossary",
    keywords: ["APT Attack", "State-Sponsored Threats", "Espionage Campaigns", "Targeted Intrusions", "Persistent Backdoors"],
    summary: "An Advanced Persistent Threat (APT) is a stealthy threat actor, typically a nation-state or state-sponsored group, which conducts high-fidelity, long-duration hacking campaigns targeting critical organizational systems.",
    faqs: [],
    parent: "/resources",
    children: []
  },
  {
    url: "/glossary/ciso",
    title: "Chief Information Security Officer (CISO) Definition | CyberTeck OS Glossary",
    description: "What is a CISO? Define the role, responsibilities, and corporate governance obligations of a Chief Information Security Officer.",
    category: "glossary",
    keywords: ["CISO", "Security Governance", "Risk Management", "Executive Officers", "Board Advisories"],
    summary: "A Chief Information Security Officer (CISO) is the senior corporate executive responsible for establishing and maintaining the enterprise vision, strategy, and program to ensure information assets are protected.",
    faqs: [],
    parent: "/resources",
    children: []
  },
  {
    url: "/glossary/vapt",
    title: "Vulnerability Assessment and Penetration Testing | CyberTeck OS Glossary",
    description: "What is VAPT? Define Vulnerability Assessment and Penetration Testing. Periodic security audits and statutory certifications.",
    category: "glossary",
    keywords: ["VAPT", "Penetration Testing", "Vulnerability Scans", "Security Auditing", "Static Code Reviews"],
    summary: "Vulnerability Assessment and Penetration Testing (VAPT) is a systematic cybersecurity auditing service that identifies, assesses, and exploits technical gaps in servers, applications, and networks.",
    faqs: [],
    parent: "/resources",
    children: []
  },
  {
    url: "/glossary/waf",
    title: "Web Application Firewall (WAF) Definition | CyberTeck OS Glossary",
    description: "What is a WAF? Learn about Web Application Firewalls, OWASP Top 10 attack filters, and API gateway shielding.",
    category: "glossary",
    keywords: ["WAF", "Web Firewall", "OWASP Top 10", "SQL Injection Filters", "XSS Shielding"],
    summary: "A Web Application Firewall (WAF) protects web applications by filtering and monitoring HTTP traffic between a web application and the Internet, defending against common OWASP Top 10 exploits.",
    faqs: [],
    parent: "/resources",
    children: []
  },
  {
    url: "/glossary/grc",
    title: "Governance, Risk, and Compliance (GRC) | CyberTeck OS Glossary",
    description: "What is GRC? Definition of Governance, Risk, and Compliance. Aligning IT operations with statutory regulations and policies.",
    category: "glossary",
    keywords: ["GRC", "Governance Processes", "Risk registries", "Regulatory alignment", "Policy Lifecycle"],
    summary: "Governance, Risk, and Compliance (GRC) is a structured, organizational strategy that aligns IT operations with legal mandates, manages corporate risks, and automates internal policies.",
    faqs: [],
    parent: "/resources",
    children: []
  },
  {
    url: "/glossary/isms",
    title: "Information Security Management System (ISMS) | CyberTeck OS Glossary",
    description: "What is an ISMS? Define Information Security Management System, ISO 27001 requirements, and policy control layouts.",
    category: "glossary",
    keywords: ["ISMS", "Security Controls", "ISO 27001 ISMS", "Risk Management Policy", "Information Governance"],
    summary: "An Information Security Management System (ISMS) is a set of policies, procedures, and physical/logical controls used by organizations to systematically manage and secure their information assets.",
    faqs: [],
    parent: "/resources",
    children: []
  },
  {
    url: "/glossary/nciipc",
    title: "National Critical Information Infrastructure Protection Centre (NCIIPC) | CyberTeck OS Glossary",
    description: "What is NCIIPC? Explore the Indian central agency protecting National Critical Information Infrastructure.",
    category: "glossary",
    keywords: ["NCIIPC", "National Security", "Critical Assets Protection", "CII Guidelines", "Central Agency"],
    summary: "NCIIPC is India's national nodal agency under the Information Technology Act 2000, specifically designated to safeguard and coordinate security responses for National Critical Information Infrastructure (CII).",
    faqs: [],
    parent: "/resources",
    children: []
  },
  {
    url: "/glossary/scada",
    title: "SCADA Industrial Telemetry Definition | CyberTeck OS Glossary",
    description: "What is SCADA? Definition of Supervisory Control and Data Acquisition. Secure smart grids and manufacturing control systems.",
    category: "glossary",
    keywords: ["SCADA", "Industrial Telemetry", "Logic Controllers", "Grid Protection", "OT Cybersecurity"],
    summary: "Supervisory Control and Data Acquisition (SCADA) is an industrial control system architecture designed to collect high-frequency machine telemetry and manage real-time automated physical processes.",
    faqs: [],
    parent: "/resources",
    children: []
  },
  {
    url: "/glossary/ot",
    title: "Operational Technology (OT) Definition | CyberTeck OS Glossary",
    description: "What is Operational Technology (OT)? Learn about OT/IT convergence, legacy hardware risks, and SCADA cybersecurity.",
    category: "glossary",
    keywords: ["Operational Technology", "OT IT Convergence", "Industrial Hardware", "PLC protection", "SCADA telemetry"],
    summary: "Operational Technology (OT) is a category of hardware and software designed to monitor and control physical equipment, valves, grids, and assets in industrial or utilities environments.",
    faqs: [],
    parent: "/resources",
    children: []
  }
];
