import {
  ShieldCheck,
  Lock,
  Eye,
  KeyRound,
  Network,
  ScanFace,
  Gauge,
  Boxes,
  Users,
  ShieldAlert,
  BadgeCheck,
  Activity,
  Layers,
  BrainCircuit,
  Smartphone,
  MapPin,
  Fingerprint,
  Timer,
} from "lucide-react";
import type { Pillar } from "@/lib/types";

export const aiIam: Pillar = {
  index: 1,
  slug: "ai-iam",
  name: "AI-Native Identity & Access Management (AI-IAM)",
  nameHighlight: "Access Management (AI-IAM)",
  clusterSectionLabel: "AI-IAM",
  clusterSubheading: "Comprehensive identity security for modern enterprises",
  whyMattersLabel: "AI-IAM Matters for Indian Enterprises",
  resourceSectionLabel: "AI-IAM",
  heroPrimaryCTA: "Book a Demo",
  tagline: "Zero Trust Identity Fabric for the AI-First Enterprise",
  description:
    "Cyberteck AI-IAM uses Agentic AI to verify every identity, every device, and every access request — continuously. Eliminate standing privileges, stop account takeovers, and build a breach-proof identity layer.",
  accentTheme: "violet",
  heroIcon: ShieldCheck,
  featureChips: [
    { icon: Network, label: "Adaptive Zero Trust" },
    { icon: Gauge, label: "Risk Scoring" },
    { icon: Eye, label: "Continuous Verification" },
    { icon: Lock, label: "Least Privilege by Default" },
  ],
  heroStatusPanel: {
    scoreCard: { label: "Identity / Risk Score", value: 18, sublabel: "Low Risk" },
    left: [
      { icon: BrainCircuit, label: "AI Risk Engine", value: "Analyzing Behavior", tone: "blue" },
      { icon: Smartphone, label: "Device Trust", value: "Trusted", tone: "green" },
      { icon: MapPin, label: "Location", value: "Bengaluru, India", tone: "blue" },
    ],
    right: [
      { icon: Lock, label: "Zero Trust Status", value: "Active", tone: "green" },
      { icon: Fingerprint, label: "MFA Status", value: "Enforced", tone: "green" },
      { icon: Timer, label: "Privilege Access", value: "JIT Access Only", tone: "blue" },
    ],
  },
  frameworks: [
    { icon: BadgeCheck, label: "DPDP Act Compliant" },
    { icon: ShieldCheck, label: "ISO 27001 Certified" },
    { icon: Activity, label: "NIST CSF Aligned" },
    { icon: ShieldAlert, label: "RBI Cyber Framework" },
    { icon: ScanFace, label: "CERT-In Ready" },
    { icon: Lock, label: "SOC 2 Type II" },
    { icon: Layers, label: "GDPR Ready" },
  ],
  clusters: [
    {
      index: 1,
      icon: KeyRound,
      title: "AI-Powered PAM",
      description: "Intelligent Privileged Access Management with behavior analytics and anomaly detection.",
      href: "/pillars/ai-iam/clusters/ai-powered-pam",
    },
    {
      index: 2,
      icon: Timer,
      title: "Just-in-Time (JIT) Access",
      description: "Grant temporary, context-aware access. No standing privileges. No hidden risks.",
      href: "/pillars/ai-iam/clusters/just-in-time-access",
    },
    {
      index: 3,
      icon: Network,
      title: "Zero Trust Architecture",
      description: "Verify explicitly, least privilege access, and assume breach.",
      href: "/pillars/ai-iam/clusters/zero-trust-architecture",
    },
    {
      index: 4,
      icon: ShieldAlert,
      title: "Identity Threat Detection",
      description: "Detect and stop account takeovers, credential stuffing & insider threats.",
      href: "/pillars/ai-iam/clusters/identity-threat-detection",
    },
    {
      index: 5,
      icon: Fingerprint,
      title: "Adaptive MFA & Authentication",
      description: "Risk-based, adaptive MFA that balances security and user experience.",
      href: "/pillars/ai-iam/clusters/adaptive-mfa-authentication",
    },
    {
      index: 6,
      icon: Users,
      title: "IGA & Lifecycle Management",
      description: "Automate joiner-mover-leaver processes and entitlement governance.",
      href: "/pillars/ai-iam/clusters/iga-lifecycle-management",
    },
    {
      index: 7,
      icon: ScanFace,
      title: "CIAM & Customer Identities",
      description: "Secure customer identity journeys with privacy-by-design.",
      href: "/pillars/ai-iam/clusters/ciam-customer-identities",
    },
    {
      index: 8,
      icon: Gauge,
      title: "Access Risk Analytics",
      description: "AI-driven risk scoring for users, roles, devices, and sessions.",
      href: "/pillars/ai-iam/clusters/access-risk-analytics",
    },
    {
      index: 9,
      icon: Boxes,
      title: "Secrets & Credential Management",
      description: "Secure storage, rotation, and zero-exposure secret management.",
      href: "/pillars/ai-iam/clusters/secrets-credential-management",
    },
    {
      index: 10,
      icon: BadgeCheck,
      title: "Identity Compliance & Audit",
      description: "Complete audit trail, certification proof and compliance automation.",
      href: "/pillars/ai-iam/clusters/identity-compliance-audit",
    },
  ],
  whyItMatters: [
    {
      icon: ShieldAlert,
      title: "87% of breaches involve compromised identities.",
      description: "— Verizon DBIR",
    },
    {
      icon: Layers,
      title: "Over-privileged access is the #1 cause of lateral movement.",
      description: "— Microsoft",
    },
    {
      icon: BrainCircuit,
      title: "AI-powered attackers exploit identity gaps in minutes.",
      description: "— CrowdStrike",
    },
    {
      icon: BadgeCheck,
      title: "Comply with DPDP Act, CERT-In, RBI, SEBI, IRDAI with ease.",
      description: "",
    },
    {
      icon: Users,
      title: "Secure workforce, customers, partners and AI agents.",
      description: "",
    },
    {
      icon: Gauge,
      title: "Reduce identity risk. Improve operational efficiency.",
      description: "",
    },
  ],
  resources: [
    { icon: KeyRound, title: "AI-Powered PAM in India Complete Guide", ctaLabel: "Download Guide", href: "/resources/ai-powered-pam-india-complete-guide" },
    { icon: Network, title: "Zero Trust Architecture Implementation", ctaLabel: "Download Guide", href: "/resources/zero-trust-architecture-implementation" },
    { icon: Timer, title: "JIT Access Best Practices for Indian Enterprises", ctaLabel: "Download Guide", href: "/resources/jit-access-best-practices-india" },
    { icon: Users, title: "IGA & Lifecycle Management Ultimate Guide", ctaLabel: "Download Guide", href: "/resources/iga-lifecycle-management-ultimate-guide" },
    { icon: Gauge, title: "AI Risk Analytics for Identity Detailed Whitepaper", ctaLabel: "Download Whitepaper", href: "/resources/ai-risk-analytics-identity-whitepaper" },
  ],
  bottomCTA: {
    headline: "Secure Every Identity. Every Access. Every Time.",
    description: "See how Cyberteck AI-IAM can transform your identity security and reduce breach risk by up to 90%.",
    checklist: [
      "Personalized Platform Walkthrough",
      "Use Cases Relevant to Your Industry",
      "Architecture & Integration Guidance",
      "ROI & Security Impact Discussion",
    ],
    primaryCTA: "Book a Demo",
    secondaryCTA: "Talk to an Expert",
  },
};
