import {
  BrainCircuit,
  ShieldCheck,
  Eye,
  Lock,
  ScanFace,
  Layers,
  Boxes,
  Radar,
  Activity,
  BadgeCheck,
  MessageSquare,
  Bot,
  Database,
  ClipboardList,
  AlertTriangle,
} from "lucide-react";
import type { Pillar } from "@/lib/types";

export const aiSecurityGovernance: Pillar = {
  index: 8,
  slug: "ai-security-governance",
  name: "AI Security & LLM Governance",
  nameHighlight: "LLM Governance",
  clusterSectionLabel: "AI Security & LLM Governance",
  clusterSubheading: "Secure every model. Govern every prompt. Trust every AI agent.",
  whyMattersLabel: "AI Security & LLM Governance",
  resourceSectionLabel: "AI Security",
  heroPrimaryCTA: "Get Free AI Security Assessment",
  tagline: "Secure Your Models. Govern Your Agents. Trust Your AI.",
  description:
    "Cyberteck's AI Security platform discovers shadow AI usage, red-teams LLM applications for prompt injection and data leakage, and enforces governance guardrails across every model and AI agent your enterprise deploys.",
  accentTheme: "violet",
  heroIcon: BrainCircuit,
  featureChips: [
    { icon: Eye, label: "Shadow AI Discovery" },
    { icon: ShieldCheck, label: "LLM Red Teaming" },
    { icon: Lock, label: "Prompt Injection Defense" },
    { icon: Bot, label: "AI Agent Governance" },
  ],
  heroStats: {
    primaryScore: {
      label: "AI Risk Score",
      value: 66,
      max: 100,
      delta: "Moderate Risk",
      deltaDirection: "down",
      trend: [82, 79, 76, 74, 71, 69, 67, 66],
    },
    supportingStats: [
      {
        label: "Shadow AI Tools Discovered",
        value: 184,
        delta: "+27.6% vs last scan",
        deltaDirection: "up",
        trend: [110, 125, 135, 145, 155, 165, 175, 184],
      },
      {
        label: "AI Agents in Production",
        value: 62,
        delta: "Monitored in Real-Time",
        deltaDirection: "up",
        trend: [30, 35, 40, 45, 50, 54, 58, 62],
      },
    ],
    donut: {
      label: "AI Risk Coverage",
      total: "184",
      segments: [
        { label: "Governed", value: 54, color: "green" },
        { label: "Under Review", value: 29, color: "amber" },
        { label: "Unsanctioned", value: 17, color: "red" },
      ],
    },
    rankedList: {
      label: "Top AI Risk Vectors",
      items: [
        { label: "Prompt Injection", pct: 29 },
        { label: "Sensitive Data Leakage", pct: 25 },
        { label: "Unsanctioned Shadow AI", pct: 21 },
        { label: "Model Hallucination Risk", pct: 15 },
        { label: "Other", pct: 10 },
      ],
    },
    progress: {
      label: "AI Governance Coverage",
      value: 72,
      sublabel: "Models & Agents Under Policy",
    },
  },
  frameworks: [
    { icon: BadgeCheck, label: "NIST AI RMF Aligned" },
    { icon: ShieldCheck, label: "ISO/IEC 42001 Ready" },
    { icon: Activity, label: "OWASP LLM Top 10 Aligned" },
    { icon: Layers, label: "DPDP Act Compliant" },
    { icon: Radar, label: "CERT-In Ready" },
    { icon: BadgeCheck, label: "SOC 2 Type II" },
  ],
  clusters: [
    { index: 1, icon: Eye, title: "Shadow AI Discovery", description: "Discover unsanctioned AI tools and LLM usage across the organization.", href: "/pillars/ai-security-governance/clusters/shadow-ai-discovery" },
    { index: 2, icon: ShieldCheck, title: "LLM Red Teaming & Testing", description: "Continuously red-team AI applications for prompt injection and jailbreaks.", href: "/pillars/ai-security-governance/clusters/llm-red-teaming" },
    { index: 3, icon: Lock, title: "Prompt Injection & Jailbreak Defense", description: "Real-time guardrails that detect and block adversarial prompts.", href: "/pillars/ai-security-governance/clusters/prompt-injection-defense" },
    { index: 4, icon: Database, title: "Sensitive Data Leakage Prevention", description: "Stop PII and confidential data from leaking through model outputs.", href: "/pillars/ai-security-governance/clusters/ai-data-leakage-prevention" },
    { index: 5, icon: Bot, title: "AI Agent Governance & Guardrails", description: "Define and enforce permission boundaries for autonomous AI agents.", href: "/pillars/ai-security-governance/clusters/ai-agent-governance" },
    { index: 6, icon: ScanFace, title: "Model Inventory & Risk Scoring", description: "Maintain a live inventory of every model in use, scored by risk.", href: "/pillars/ai-security-governance/clusters/model-inventory-risk-scoring" },
    { index: 7, icon: MessageSquare, title: "AI Usage Policy & Access Control", description: "Enforce who can use which models, with what data, under what policy.", href: "/pillars/ai-security-governance/clusters/ai-usage-policy-access-control" },
    { index: 8, icon: AlertTriangle, title: "AI Incident Detection & Response", description: "Detect and respond to AI-specific incidents like model abuse or data exfiltration.", href: "/pillars/ai-security-governance/clusters/ai-incident-detection-response" },
    { index: 9, icon: ClipboardList, title: "AI Governance & Audit Trail", description: "Maintain auditable records of model decisions, prompts, and outputs.", href: "/pillars/ai-security-governance/clusters/ai-governance-audit-trail" },
    { index: 10, icon: Activity, title: "AI Risk Analytics & Reporting", description: "Executive dashboards tracking AI risk posture across the enterprise.", href: "/pillars/ai-security-governance/clusters/ai-risk-analytics-reporting" },
  ],
  whyItMatters: [
    { icon: Eye, title: "See Every AI Tool in Use", description: "Shadow AI is the new shadow IT — find it before it finds a headline." },
    { icon: Lock, title: "Stop Prompt Injection Attacks", description: "The #1 threat vector unique to LLM applications." },
    { icon: Database, title: "Prevent Data Leakage", description: "Keep confidential data out of model outputs and logs." },
    { icon: Bot, title: "Govern Autonomous Agents", description: "Set guardrails before agents take real-world actions." },
    { icon: BadgeCheck, title: "Get Ahead of AI Regulation", description: "Build governance ahead of emerging AI compliance requirements." },
    { icon: ShieldCheck, title: "Build Trustworthy AI", description: "Ship AI features your customers and regulators can trust." },
  ],
  resources: [
    { icon: Eye, title: "Shadow AI Discovery Guide", ctaLabel: "Download Guide", href: "/resources/shadow-ai-discovery-guide" },
    { icon: ShieldCheck, title: "LLM Red Teaming Playbook", ctaLabel: "Download Playbook", href: "/resources/llm-red-teaming-playbook" },
    { icon: Lock, title: "Prompt Injection Defense Checklist", ctaLabel: "Download Checklist", href: "/resources/prompt-injection-defense-checklist" },
    { icon: Bot, title: "AI Agent Governance Framework", ctaLabel: "Download Framework", href: "/resources/ai-agent-governance-framework" },
    { icon: BadgeCheck, title: "AI Governance Maturity Model", ctaLabel: "View Model", href: "/resources/ai-governance-maturity-model" },
    { icon: Activity, title: "AI Threat Landscape Report 2026", ctaLabel: "Download Report", href: "/resources/ai-threat-landscape-report-2026" },
  ],
  bottomCTA: {
    headline: "Secure Your AI. Govern Every Agent. Build Trust.",
    description: "Get complete visibility and control over every model, prompt, and AI agent in your enterprise.",
    checklist: [
      "Shadow AI Discovery Scan",
      "LLM Red Team Assessment",
      "Agent Governance Review",
      "No Obligation. No Credit Card.",
    ],
    primaryCTA: "Get Free AI Security Assessment",
    secondaryCTA: "Talk to an AI Security Expert",
  },
};
