import {
  GitBranch,
  ShieldCheck,
  Code,
  Bug,
  Layers,
  Boxes,
  Radar,
  Activity,
  BadgeCheck,
  Workflow,
  Puzzle,
  Server,
  ClipboardList,
  ScanLine,
  Zap,
} from "lucide-react";
import type { Pillar } from "@/lib/types";

export const appSecurity: Pillar = {
  index: 4,
  slug: "application-security",
  name: "AI-Native Application & DevSecOps Security",
  nameHighlight: "Application & DevSecOps Security",
  clusterSectionLabel: "AI-Native Application Security",
  clusterSubheading: "Secure code from commit to production. Ship fast without shipping vulnerabilities.",
  whyMattersLabel: "AI-Native Application Security",
  resourceSectionLabel: "AppSec",
  heroPrimaryCTA: "Get Free AppSec Assessment",
  tagline: "Find Vulnerabilities Early. Fix Them Fast. Ship With Confidence.",
  description:
    "Cyberteck's AI-native application security platform embeds security into every stage of the SDLC — from SAST and SCA in the IDE to DAST and API security in production — so vulnerabilities are caught before they reach users.",
  accentTheme: "amber",
  heroIcon: Code,
  featureChips: [
    { icon: Code, label: "Shift-Left SAST/SCA" },
    { icon: Zap, label: "AI-Powered Triage" },
    { icon: Workflow, label: "CI/CD Native Integration" },
    { icon: Bug, label: "Runtime API Protection" },
  ],
  heroStats: {
    primaryScore: {
      label: "AppSec Posture Score",
      value: 74,
      max: 100,
      delta: "Improving",
      deltaDirection: "up",
      trend: [50, 55, 58, 62, 65, 68, 71, 74],
    },
    supportingStats: [
      {
        label: "Open Vulnerabilities",
        value: 512,
        delta: "-21.3% vs last sprint",
        deltaDirection: "down",
        trend: [720, 690, 660, 630, 600, 570, 540, 512],
      },
      {
        label: "Repositories Scanned",
        value: "1,180",
        delta: "+11.4% vs last month",
        deltaDirection: "up",
        trend: [900, 950, 1000, 1040, 1080, 1120, 1150, 1180],
      },
    ],
    donut: {
      label: "Vulnerability Severity",
      total: "512",
      segments: [
        { label: "Critical/High", value: 18, color: "red" },
        { label: "Medium", value: 46, color: "amber" },
        { label: "Low", value: 36, color: "green" },
      ],
    },
    rankedList: {
      label: "Top Vulnerability Classes",
      items: [
        { label: "Injection Flaws", pct: 27 },
        { label: "Vulnerable Dependencies", pct: 24 },
        { label: "Broken Access Control", pct: 20 },
        { label: "Insecure API Design", pct: 17 },
        { label: "Other", pct: 12 },
      ],
    },
    progress: {
      label: "CI/CD Pipeline Coverage",
      value: 88,
      sublabel: "Repos with Automated Scanning",
    },
  },
  frameworks: [
    { icon: BadgeCheck, label: "OWASP ASVS Aligned" },
    { icon: ShieldCheck, label: "ISO 27001 Certified" },
    { icon: Activity, label: "NIST SSDF Aligned" },
    { icon: Layers, label: "SOC 2 Type II" },
    { icon: Radar, label: "CERT-In Ready" },
    { icon: BadgeCheck, label: "DPDP Act Compliant" },
  ],
  clusters: [
    { index: 1, icon: Code, title: "Static Application Security Testing (SAST)", description: "Scan source code for vulnerabilities directly in the IDE and pull requests.", href: "/pillars/application-security/clusters/sast" },
    { index: 2, icon: Boxes, title: "Software Composition Analysis (SCA)", description: "Detect vulnerable and outdated open-source dependencies automatically.", href: "/pillars/application-security/clusters/sca" },
    { index: 3, icon: ScanLine, title: "Dynamic Application Security Testing (DAST)", description: "Test running applications for exploitable vulnerabilities pre-production.", href: "/pillars/application-security/clusters/dast" },
    { index: 4, icon: Puzzle, title: "API Security Testing & Protection", description: "Discover shadow APIs and protect against injection, abuse, and data exposure.", href: "/pillars/application-security/clusters/api-security" },
    { index: 5, icon: Workflow, title: "CI/CD Pipeline Security", description: "Embed security gates into build pipelines without slowing developers down.", href: "/pillars/application-security/clusters/cicd-pipeline-security" },
    { index: 6, icon: Bug, title: "AI-Powered Vulnerability Triage", description: "Automatically prioritize findings by exploitability and business impact.", href: "/pillars/application-security/clusters/ai-vulnerability-triage" },
    { index: 7, icon: Server, title: "Container & Infrastructure Scanning", description: "Scan container images and IaC templates for vulnerabilities before deploy.", href: "/pillars/application-security/clusters/container-infrastructure-scanning" },
    { index: 8, icon: GitBranch, title: "Secrets Detection in Code", description: "Find hardcoded credentials, API keys, and tokens before they're exposed.", href: "/pillars/application-security/clusters/secrets-detection-in-code" },
    { index: 9, icon: ClipboardList, title: "Vulnerability Remediation Workflows", description: "Route findings to the right developer with fix guidance and SLAs.", href: "/pillars/application-security/clusters/vulnerability-remediation-workflows" },
    { index: 10, icon: Activity, title: "AppSec Analytics & Reporting", description: "Track vulnerability trends, MTTR, and coverage across every repository.", href: "/pillars/application-security/clusters/appsec-analytics-reporting" },
  ],
  whyItMatters: [
    { icon: Zap, title: "Catch Bugs Before Production", description: "Fix vulnerabilities where they're cheapest — in the IDE." },
    { icon: Bug, title: "Cut Through Alert Fatigue", description: "AI triage surfaces the vulnerabilities that actually matter." },
    { icon: Workflow, title: "Keep Developers Moving Fast", description: "Security gates that don't break the build pipeline." },
    { icon: Boxes, title: "Manage Open-Source Risk", description: "Know exactly which dependencies carry known CVEs." },
    { icon: Puzzle, title: "Secure Your API Surface", description: "APIs are the new perimeter — protect them directly." },
    { icon: BadgeCheck, title: "Build Audit-Ready Software", description: "Evidence of secure development, automatically collected." },
  ],
  resources: [
    { icon: Code, title: "SAST Implementation Guide", ctaLabel: "Download Guide", href: "/resources/sast-implementation-guide" },
    { icon: Boxes, title: "SCA Buyer's Checklist", ctaLabel: "Download Checklist", href: "/resources/sca-buyers-checklist" },
    { icon: Workflow, title: "CI/CD Security Playbook", ctaLabel: "Download Playbook", href: "/resources/cicd-security-playbook" },
    { icon: Puzzle, title: "API Security Best Practices", ctaLabel: "Download Guide", href: "/resources/api-security-best-practices" },
    { icon: Bug, title: "AppSec Maturity Model", ctaLabel: "View Model", href: "/resources/appsec-maturity-model" },
    { icon: Activity, title: "Vulnerability Trends Report 2026", ctaLabel: "Download Report", href: "/resources/vulnerability-trends-report-2026" },
  ],
  bottomCTA: {
    headline: "Ship Secure Code. Ship It Fast. Every Time.",
    description: "Embed AI-native security into every stage of your SDLC — from the first commit to production.",
    checklist: [
      "Repository Security Scan",
      "CI/CD Integration Review",
      "Vulnerability Triage Demo",
      "No Obligation. No Credit Card.",
    ],
    primaryCTA: "Get Free AppSec Assessment",
    secondaryCTA: "Talk to an AppSec Expert",
  },
};
