import {
  Cloud,
  ShieldCheck,
  Network,
  Lock,
  Eye,
  Gauge,
  Layers,
  Boxes,
  Radar,
  Activity,
  BadgeCheck,
  Settings,
  GitBranch,
  Database,
  ClipboardList,
} from "lucide-react";
import type { Pillar } from "@/lib/types";

export const cloudSecurity: Pillar = {
  index: 2,
  slug: "cloud-security",
  name: "AI-Native Cloud Security",
  nameHighlight: "Cloud Security",
  clusterSectionLabel: "AI-Native Cloud Security",
  clusterSubheading: "Continuous posture management. Multi-cloud visibility. Automated remediation.",
  whyMattersLabel: "AI-Native Cloud Security",
  resourceSectionLabel: "Cloud Security",
  heroPrimaryCTA: "Get Free Cloud Security Assessment",
  tagline: "See Every Cloud. Fix Every Misconfiguration. Ship Securely.",
  description:
    "Cyberteck's AI-native cloud security platform continuously discovers, assesses, and remediates risk across AWS, Azure, and GCP — unifying CSPM, CIEM, and cloud workload protection into one control plane.",
  accentTheme: "cyan",
  heroIcon: Cloud,
  featureChips: [
    { icon: Cloud, label: "Multi-Cloud Visibility" },
    { icon: Gauge, label: "Continuous Posture Scoring" },
    { icon: GitBranch, label: "Shift-Left Remediation" },
    { icon: Lock, label: "Least-Privilege Cloud IAM" },
  ],
  heroStats: {
    primaryScore: {
      label: "Cloud Security Score",
      value: 81,
      max: 100,
      delta: "Good Posture",
      deltaDirection: "up",
      trend: [55, 60, 62, 66, 70, 74, 78, 81],
    },
    supportingStats: [
      {
        label: "Misconfigurations Found",
        value: "1,942",
        delta: "-14.6% vs last month",
        deltaDirection: "down",
        trend: [40, 38, 36, 34, 33, 31, 30, 28],
      },
      {
        label: "Cloud Assets Monitored",
        value: "24,600+",
        delta: "+9.2% vs last month",
        deltaDirection: "up",
        trend: [18, 19, 20, 21, 22, 23, 24, 24.6],
      },
    ],
    donut: {
      label: "Remediation Status",
      total: "1,942",
      segments: [
        { label: "Auto-Remediated", value: 58, color: "green" },
        { label: "In Progress", value: 27, color: "amber" },
        { label: "Open", value: 15, color: "red" },
      ],
    },
    rankedList: {
      label: "Top Cloud Risks",
      items: [
        { label: "Public Storage Buckets", pct: 28 },
        { label: "Over-Permissive IAM Roles", pct: 24 },
        { label: "Unencrypted Data at Rest", pct: 20 },
        { label: "Exposed Management Ports", pct: 16 },
        { label: "Other", pct: 12 },
      ],
    },
    progress: {
      label: "Multi-Cloud Coverage",
      value: 91,
      sublabel: "AWS, Azure & GCP Accounts",
    },
  },
  frameworks: [
    { icon: BadgeCheck, label: "ISO 27017 Aligned" },
    { icon: ShieldCheck, label: "CIS Benchmarks" },
    { icon: Activity, label: "NIST CSF Aligned" },
    { icon: Lock, label: "SOC 2 Type II" },
    { icon: Layers, label: "DPDP Act Compliant" },
    { icon: Radar, label: "CERT-In Ready" },
    { icon: Boxes, label: "RBI Cyber Framework" },
  ],
  clusters: [
    { index: 1, icon: Gauge, title: "Cloud Security Posture Management (CSPM)", description: "Continuously scan cloud accounts for misconfigurations against best-practice benchmarks.", href: "/pillars/cloud-security/clusters/cspm" },
    { index: 2, icon: Lock, title: "Cloud Infrastructure Entitlement Management (CIEM)", description: "Right-size cloud IAM permissions and eliminate toxic privilege combinations.", href: "/pillars/cloud-security/clusters/ciem" },
    { index: 3, icon: Boxes, title: "Container & Kubernetes Security", description: "Scan images, enforce policies, and secure running workloads across clusters.", href: "/pillars/cloud-security/clusters/container-kubernetes-security" },
    { index: 4, icon: GitBranch, title: "Infrastructure-as-Code Security", description: "Catch misconfigurations in Terraform, CloudFormation, and Helm before deploy.", href: "/pillars/cloud-security/clusters/iac-security" },
    { index: 5, icon: Network, title: "Cloud Network Security", description: "Detect exposed ports, insecure security groups, and unintended internet-facing assets.", href: "/pillars/cloud-security/clusters/cloud-network-security" },
    { index: 6, icon: Database, title: "Data Security Posture in the Cloud", description: "Discover and classify sensitive data across cloud storage and databases.", href: "/pillars/cloud-security/clusters/cloud-data-security-posture" },
    { index: 7, icon: Radar, title: "Cloud Threat Detection", description: "Detect anomalous API calls, credential misuse, and lateral movement in cloud environments.", href: "/pillars/cloud-security/clusters/cloud-threat-detection" },
    { index: 8, icon: Settings, title: "Cloud Workload Protection (CWPP)", description: "Runtime protection for VMs, serverless functions, and containers.", href: "/pillars/cloud-security/clusters/cloud-workload-protection" },
    { index: 9, icon: ClipboardList, title: "Cloud Compliance & Benchmarking", description: "Map cloud controls to CIS, ISO, DPDP, and RBI requirements automatically.", href: "/pillars/cloud-security/clusters/cloud-compliance-benchmarking" },
    { index: 10, icon: Activity, title: "Cloud Risk Analytics & Reporting", description: "Executive dashboards showing cloud risk trends across every account and region.", href: "/pillars/cloud-security/clusters/cloud-risk-analytics-reporting" },
  ],
  whyItMatters: [
    { icon: Eye, title: "Eliminate Blind Spots", description: "See every account, region, and service in one place." },
    { icon: ShieldCheck, title: "Stop Misconfiguration Breaches", description: "The #1 cause of cloud data breaches, fixed automatically." },
    { icon: Gauge, title: "Shift Security Left", description: "Catch risk in IaC before it ever reaches production." },
    { icon: BadgeCheck, title: "Simplify Multi-Cloud Compliance", description: "One dashboard for CIS, ISO, DPDP, and RBI." },
    { icon: Lock, title: "Enforce Least Privilege in the Cloud", description: "Right-size IAM roles across every provider." },
    { icon: Activity, title: "Move Faster, Safely", description: "Give developers guardrails, not gatekeepers." },
  ],
  resources: [
    { icon: Gauge, title: "CSPM Implementation Guide", ctaLabel: "Download Guide", href: "/resources/cspm-implementation-guide" },
    { icon: Boxes, title: "Kubernetes Security Checklist", ctaLabel: "Download Checklist", href: "/resources/kubernetes-security-checklist" },
    { icon: GitBranch, title: "IaC Security Playbook", ctaLabel: "Download Playbook", href: "/resources/iac-security-playbook" },
    { icon: Lock, title: "CIEM Buyer's Guide", ctaLabel: "Download Guide", href: "/resources/ciem-buyers-guide-cloud" },
    { icon: BadgeCheck, title: "Cloud Compliance Mapping Template", ctaLabel: "Download Template", href: "/resources/cloud-compliance-mapping-template" },
    { icon: Activity, title: "Cloud Risk Dashboard", ctaLabel: "View Dashboard", href: "/resources/cloud-risk-dashboard" },
  ],
  bottomCTA: {
    headline: "See Every Cloud. Fix Every Risk. Automatically.",
    description: "Get complete visibility and automated remediation across your entire multi-cloud footprint.",
    checklist: [
      "Multi-Cloud Posture Assessment",
      "Misconfiguration Risk Report",
      "IAM Entitlement Review",
      "No Obligation. No Credit Card.",
    ],
    primaryCTA: "Get Free Cloud Security Assessment",
    secondaryCTA: "Talk to a Cloud Security Expert",
  },
};
