import {
  Database,
  ShieldCheck,
  Eye,
  Lock,
  ScanFace,
  Layers,
  Boxes,
  Radar,
  Activity,
  BadgeCheck,
  FileText,
  Fingerprint,
  Share2,
  ClipboardList,
  Trash2,
} from "lucide-react";
import type { Pillar } from "@/lib/types";

export const dataSecurity: Pillar = {
  index: 3,
  slug: "data-security",
  name: "AI-Powered Data Security & Privacy",
  nameHighlight: "Data Security & Privacy",
  clusterSectionLabel: "AI-Powered Data Security & Privacy",
  clusterSubheading: "Discover every dataset. Classify every record. Protect what matters.",
  whyMattersLabel: "AI-Powered Data Security & Privacy",
  resourceSectionLabel: "Data Security",
  heroPrimaryCTA: "Get Free Data Risk Assessment",
  tagline: "Know Your Data. Classify Every Record. Protect It Everywhere.",
  description:
    "Cyberteck's data security platform uses AI to discover, classify, and protect sensitive data across cloud, SaaS, and on-prem systems — automating DPDP Act compliance and stopping data exfiltration before it happens.",
  accentTheme: "green",
  heroIcon: Database,
  featureChips: [
    { icon: Eye, label: "Automated Data Discovery" },
    { icon: ScanFace, label: "AI-Powered Classification" },
    { icon: Lock, label: "Data Loss Prevention" },
    { icon: BadgeCheck, label: "DPDP-Ready Controls" },
  ],
  heroStats: {
    primaryScore: {
      label: "Data Risk Score",
      value: 71,
      max: 100,
      delta: "Moderate Risk",
      deltaDirection: "down",
      trend: [85, 82, 80, 78, 76, 74, 72, 71],
    },
    supportingStats: [
      {
        label: "Sensitive Records Discovered",
        value: "8.2M",
        delta: "+22.1% vs last scan",
        deltaDirection: "up",
        trend: [5.5, 6.0, 6.5, 7.0, 7.4, 7.8, 8.0, 8.2],
      },
      {
        label: "Data Exposure Incidents",
        value: 37,
        delta: "-19.4% vs last month",
        deltaDirection: "down",
        trend: [58, 54, 50, 47, 44, 41, 39, 37],
      },
    ],
    donut: {
      label: "Data Classification",
      total: "8.2M",
      segments: [
        { label: "Public", value: 42, color: "green" },
        { label: "Internal", value: 38, color: "amber" },
        { label: "Restricted / PII", value: 20, color: "red" },
      ],
    },
    rankedList: {
      label: "Top Data Risks",
      items: [
        { label: "Unclassified PII", pct: 30 },
        { label: "Over-Shared Files", pct: 26 },
        { label: "Stale Sensitive Data", pct: 19 },
        { label: "Unencrypted Databases", pct: 15 },
        { label: "Other", pct: 10 },
      ],
    },
    progress: {
      label: "DPDP Act Data Mapping",
      value: 84,
      sublabel: "Personal Data Inventory Complete",
    },
  },
  frameworks: [
    { icon: BadgeCheck, label: "DPDP Act Compliant" },
    { icon: ShieldCheck, label: "ISO 27001 Certified" },
    { icon: Layers, label: "GDPR Aligned" },
    { icon: Lock, label: "SOC 2 Type II" },
    { icon: Activity, label: "RBI Guidelines" },
    { icon: Radar, label: "SEBI Compliant" },
    { icon: BadgeCheck, label: "CERT-In Ready" },
  ],
  clusters: [
    { index: 1, icon: Eye, title: "Data Discovery & Inventory", description: "Automatically discover structured and unstructured data across every system.", href: "/pillars/data-security/clusters/data-discovery-inventory" },
    { index: 2, icon: ScanFace, title: "AI-Powered Data Classification", description: "Classify data by sensitivity, type, and regulatory category using AI models.", href: "/pillars/data-security/clusters/ai-data-classification" },
    { index: 3, icon: Lock, title: "Data Loss Prevention (DLP)", description: "Detect and block unauthorized data movement across email, cloud, and endpoints.", href: "/pillars/data-security/clusters/data-loss-prevention" },
    { index: 4, icon: Share2, title: "Data Access & Sharing Governance", description: "Monitor and control who has access to sensitive data, and how it's shared.", href: "/pillars/data-security/clusters/data-access-sharing-governance" },
    { index: 5, icon: BadgeCheck, title: "DPDP Act Compliance Automation", description: "Map personal data flows, consent, and grievance workflows to the DPDP Act.", href: "/pillars/data-security/clusters/dpdp-act-compliance-automation" },
    { index: 6, icon: Database, title: "Database & Data Warehouse Security", description: "Secure structured data stores with encryption, masking, and access controls.", href: "/pillars/data-security/clusters/database-warehouse-security" },
    { index: 7, icon: FileText, title: "Data Retention & Lifecycle Management", description: "Automate retention schedules and secure disposal of data no longer needed.", href: "/pillars/data-security/clusters/data-retention-lifecycle-management" },
    { index: 8, icon: Radar, title: "Data Exfiltration Detection", description: "Detect anomalous data transfers indicating insider threats or breaches.", href: "/pillars/data-security/clusters/data-exfiltration-detection" },
    { index: 9, icon: Trash2, title: "Data Minimization & Cleanup", description: "Identify and remediate redundant, obsolete, or over-retained data (ROT).", href: "/pillars/data-security/clusters/data-minimization-cleanup" },
    { index: 10, icon: ClipboardList, title: "Data Risk Analytics & Reporting", description: "Real-time dashboards tracking data risk posture and compliance readiness.", href: "/pillars/data-security/clusters/data-risk-analytics-reporting" },
  ],
  whyItMatters: [
    { icon: Eye, title: "Know Where Your Data Lives", description: "Discover shadow data across cloud, SaaS, and on-prem." },
    { icon: BadgeCheck, title: "Automate DPDP Act Compliance", description: "Turn a manual mapping exercise into a continuous process." },
    { icon: Lock, title: "Prevent Costly Data Breaches", description: "Stop exfiltration before sensitive data leaves your perimeter." },
    { icon: ScanFace, title: "Classify at Machine Speed", description: "AI classification scales where manual tagging can't." },
    { icon: Share2, title: "Govern Sharing & Access", description: "Know exactly who can see what, and revoke it in one click." },
    { icon: Trash2, title: "Reduce Your Attack Surface", description: "Less unnecessary data means less to lose in a breach." },
  ],
  resources: [
    { icon: Eye, title: "Data Discovery Implementation Guide", ctaLabel: "Download Guide", href: "/resources/data-discovery-implementation-guide" },
    { icon: BadgeCheck, title: "DPDP Act Compliance Toolkit", ctaLabel: "Download Toolkit", href: "/resources/dpdp-act-data-compliance-toolkit" },
    { icon: Lock, title: "DLP Deployment Playbook", ctaLabel: "Download Playbook", href: "/resources/dlp-deployment-playbook" },
    { icon: ScanFace, title: "Data Classification Maturity Model", ctaLabel: "View Model", href: "/resources/data-classification-maturity-model" },
    { icon: FileText, title: "Data Retention Policy Template", ctaLabel: "Download Template", href: "/resources/data-retention-policy-template" },
    { icon: Radar, title: "Data Exfiltration Threat Report", ctaLabel: "Download Report", href: "/resources/data-exfiltration-threat-report" },
  ],
  bottomCTA: {
    headline: "Know Your Data. Protect Every Record. Prove Compliance.",
    description: "Discover, classify, and protect sensitive data everywhere it lives — and stay DPDP-ready continuously.",
    checklist: [
      "Complete Data Discovery Scan",
      "DPDP Act Gap Analysis",
      "DLP Readiness Review",
      "No Obligation. No Credit Card.",
    ],
    primaryCTA: "Get Free Data Risk Assessment",
    secondaryCTA: "Talk to a Data Security Expert",
  },
};
