import {
  BrainCircuit,
  FileText,
  Network,
  Radar,
  Database,
  Activity,
  ClipboardList,
  ShieldCheck,
  Building2,
  BarChart3,
  Lightbulb,
  Scale,
  Lock,
  BadgeCheck,
  Layers,
  Gavel,
} from "lucide-react";
import type { Pillar } from "@/lib/types";

export const governancePolicyCompliance: Pillar = {
  index: 6,
  slug: "governance-policy-compliance",
  name: "AI-Powered Governance, Policy & Compliance (GPC)",
  nameHighlight: "Governance, Policy & Compliance (GPC)",
  clusterSectionLabel: "AI-Powered GPC",
  clusterSubheading: "Intelligent governance. Automated compliance. Continuous assurance.",
  whyMattersLabel: "AI-Powered GPC",
  resourceSectionLabel: "GPC",
  heroPrimaryCTA: "Get Free Compliance Health Check",
  tagline: "Govern Smarter. Comply Faster. Prove Continuously.",
  description:
    "Cyberteck's Agentic AI transforms governance, policy management and compliance from a manual burden into an autonomous, continuous, and audit-ready system. From DPDP Act to ISO 27001, we embed intelligence into every control.",
  accentTheme: "violet",
  heroIcon: BrainCircuit,
  whyMattersIcon: Scale,
  bottomCTAIcon: Gavel,
  featureChips: [
    { icon: FileText, label: "Policy Automation" },
    { icon: Network, label: "Control Mapping" },
    { icon: Database, label: "Evidence Collection" },
    { icon: Activity, label: "Continuous Compliance" },
  ],
  heroStats: {
    primaryScore: {
      label: "Compliance Score",
      value: 92,
      max: 100,
      delta: "Excellent",
      deltaDirection: "up",
      trend: [70, 74, 78, 80, 84, 88, 90, 92],
    },
    supportingStats: [
      {
        label: "Controls Monitored",
        value: "1,248",
        delta: "+18.3% vs last month",
        deltaDirection: "up",
        trend: [30, 32, 34, 33, 36, 38, 39, 41],
      },
      {
        label: "Policies Automated",
        value: 642,
        delta: "+24.5% vs last month",
        deltaDirection: "up",
        trend: [15, 17, 19, 21, 20, 22, 24, 26],
      },
    ],
    donut: {
      label: "Audit Readiness",
      total: "1,248",
      segments: [
        { label: "Ready", value: 68, color: "green" },
        { label: "In Progress", value: 22, color: "amber" },
        { label: "Gaps", value: 10, color: "red" },
      ],
    },
    rankedList: {
      label: "Compliance Frameworks",
      items: [
        { label: "DPDP Act 2023", pct: 100 },
        { label: "ISO 27001:2022", pct: 92 },
        { label: "NIST CSF 2.0", pct: 88 },
        { label: "RBI Cyber Framework", pct: 85 },
        { label: "SEBI Guidelines", pct: 80 },
      ],
    },
    progress: {
      label: "Overall Audit Readiness",
      value: 68,
      sublabel: "Ready for Certification",
    },
  },
  frameworks: [
    { icon: BadgeCheck, label: "DPDP Act Compliant" },
    { icon: ShieldCheck, label: "ISO 27001:2022 Certified" },
    { icon: Activity, label: "NIST CSF Aligned" },
    { icon: Scale, label: "RBI Cyber Framework" },
    { icon: Layers, label: "SEBI Guidelines" },
    { icon: Radar, label: "CERT-In Guidelines" },
    { icon: Lock, label: "SOC 2 Type II" },
    { icon: BadgeCheck, label: "GDPR Aligned" },
  ],
  clusters: [
    {
      index: 1,
      icon: FileText,
      title: "Policy Lifecycle Management",
      description: "Create, review, approve, publish, and retire policies with AI-driven workflows and version control.",
      href: "/pillars/governance-policy-compliance/clusters/policy-lifecycle-management",
    },
    {
      index: 2,
      icon: Network,
      title: "Control Mapping & Automation",
      description: "Map controls across frameworks, automate control implementation, and manage dependencies.",
      href: "/pillars/governance-policy-compliance/clusters/control-mapping-automation",
    },
    {
      index: 3,
      icon: Radar,
      title: "Regulatory Change Intelligence",
      description: "AI monitors legal and regulatory changes and assesses impact on your organization.",
      href: "/pillars/governance-policy-compliance/clusters/regulatory-change-intelligence",
    },
    {
      index: 4,
      icon: Database,
      title: "Evidence Collection & Management",
      description: "Automatically collect, validate, and store evidence with cryptographic integrity and traceability.",
      href: "/pillars/governance-policy-compliance/clusters/evidence-collection-management",
    },
    {
      index: 5,
      icon: Activity,
      title: "Continuous Compliance Monitoring",
      description: "Continuously monitor controls, policies, and configurations for real-time compliance posture visibility.",
      href: "/pillars/governance-policy-compliance/clusters/continuous-compliance-monitoring",
    },
    {
      index: 6,
      icon: ClipboardList,
      title: "Audit Management & Workflow",
      description: "Plan, execute, and close audits with automated workflows and stakeholder collaboration.",
      href: "/pillars/governance-policy-compliance/clusters/audit-management-workflow",
    },
    {
      index: 7,
      icon: ShieldCheck,
      title: "Risk & Control Self Assessment",
      description: "Automate RCSA, collect attestations, and track action plans to reduce residual risk.",
      href: "/pillars/governance-policy-compliance/clusters/risk-control-self-assessment",
    },
    {
      index: 8,
      icon: Building2,
      title: "Third-Party & Vendor Governance",
      description: "Onboard, assess, and continuously monitor vendors for security and compliance alignment.",
      href: "/pillars/governance-policy-compliance/clusters/third-party-vendor-governance",
    },
    {
      index: 9,
      icon: BarChart3,
      title: "Compliance Reporting & Dashboards",
      description: "Generate regulator-ready reports and executive dashboards in real time with AI insights.",
      href: "/pillars/governance-policy-compliance/clusters/compliance-reporting-dashboards",
    },
    {
      index: 10,
      icon: Lightbulb,
      title: "Governance Intelligence & Insights",
      description: "AI-driven insights, trends, and recommendations to strengthen governance and reduce risk.",
      href: "/pillars/governance-policy-compliance/clusters/governance-intelligence-insights",
    },
  ],
  whyItMatters: [
    { icon: Activity, title: "Eliminate Manual Overhead", description: "Reduce compliance effort by up to 70% with automation." },
    { icon: ShieldCheck, title: "Always Audit-Ready", description: "Maintain continuous state of compliance, always." },
    { icon: BadgeCheck, title: "Reduce Risk & Penalties", description: "Identify gaps early and avoid regulatory penalties." },
    { icon: Building2, title: "Unified Compliance Command Center", description: "One platform. All frameworks. Complete visibility." },
    { icon: Scale, title: "Build Trust & Governance", description: "Strengthen stakeholder trust with transparency." },
    { icon: Lightbulb, title: "Faster Decisions", description: "AI insights help you govern and act with confidence." },
  ],
  resources: [
    { icon: FileText, title: "AI Policy Automation Guide", ctaLabel: "Download eBook", href: "/resources/ai-policy-automation-guide" },
    { icon: Network, title: "Control Mapping Playbook", ctaLabel: "Download Template", href: "/resources/control-mapping-playbook" },
    { icon: BadgeCheck, title: "DPDP Act Compliance Toolkit", ctaLabel: "Download Toolkit", href: "/resources/dpdp-act-compliance-toolkit" },
    { icon: ShieldCheck, title: "ISO 27001:2022 Implementation Guide", ctaLabel: "Download eBook", href: "/resources/iso-27001-2022-implementation-guide" },
    { icon: ClipboardList, title: "Audit Readiness Checklist", ctaLabel: "Download Checklist", href: "/resources/audit-readiness-checklist" },
    { icon: BarChart3, title: "Compliance Reporting Templates", ctaLabel: "Download Template", href: "/resources/compliance-reporting-templates" },
  ],
  bottomCTA: {
    headline: "Automate Governance. Assure Compliance. Build Trust.",
    description: "Cyberteck's AI-powered GPC platform helps you govern smarter, comply faster, and stay audit-ready—always.",
    checklist: [
      "Personalized Compliance Assessment",
      "Framework Gap Analysis",
      "Actionable Recommendations",
      "No Obligation. No Credit Card.",
    ],
    primaryCTA: "Get Free Compliance Health Check",
    secondaryCTA: "Talk to a GPC Expert",
  },
};
