import {
  ShieldCheck,
  Lock,
  Eye,
  Fingerprint,
  KeyRound,
  Network,
  ScanFace,
  Gauge,
  Boxes,
  Users,
  ShieldAlert,
  BadgeCheck,
  Activity,
  Layers,
  BrainCircuit,
} from "lucide-react";
import type { Pillar } from "@/lib/types";

export const identitySecurityZeroTrust: Pillar = {
  index: 7,
  slug: "identity-security-zero-trust",
  name: "AI Identity Security & Zero Trust",
  nameHighlight: "& Zero Trust",
  clusterSectionLabel: "AI Identity Security & Zero Trust",
  clusterSubheading: "Comprehensive identity protection. Continuous verification. Zero trust everywhere.",
  whyMattersLabel: "AI Identity Security & Zero Trust",
  resourceSectionLabel: "Identity Security",
  heroPrimaryCTA: "Get Free Identity Security Assessment",
  tagline: "Verify Every Identity. Authorize Every Action. Trust Nothing. Secure Everything.",
  description:
    "Cyberteck's AI-native identity security platform unifies IAM, PAM, IGA, and Zero Trust Network Access (ZTNA) with continuous verification. Stop identity-based attacks, privilege abuse, and lateral movement—before they happen.",
  accentTheme: "blue",
  heroIcon: ShieldCheck,
  featureChips: [
    { icon: ShieldCheck, label: "Zero Trust by Design" },
    { icon: BrainCircuit, label: "AI-Powered Risk Engine" },
    { icon: Lock, label: "Least Privilege Access" },
    { icon: Eye, label: "Continuous Verification" },
  ],
  heroStats: {
    primaryScore: {
      label: "Identity Risk Score",
      value: 89,
      max: 100,
      delta: "High Security Posture",
      deltaDirection: "up",
      trend: [40, 55, 48, 62, 70, 65, 80, 89],
    },
    supportingStats: [
      {
        label: "High Risk Identities",
        value: 248,
        delta: "+18.3% vs last month",
        deltaDirection: "up",
        trend: [10, 14, 12, 18, 22, 20, 24, 30],
      },
      {
        label: "Privileged Accounts",
        value: "1,356",
        delta: "Monitored in Real-Time",
        deltaDirection: "up",
        trend: [30, 32, 31, 34, 33, 35, 36, 38],
      },
    ],
    donut: {
      label: "Access Decisions (24H)",
      total: "12,847",
      segments: [
        { label: "Allowed", value: 92.1, color: "green" },
        { label: "Blocked", value: 6.4, color: "red" },
        { label: "Challenged", value: 1.5, color: "amber" },
      ],
    },
    rankedList: {
      label: "Top Risk Factors",
      items: [
        { label: "Impossible Travel", pct: 32 },
        { label: "Privilege Escalation", pct: 24 },
        { label: "Anomalous Behavior", pct: 20 },
        { label: "Excessive Access", pct: 14 },
        { label: "Other", pct: 10 },
      ],
    },
    progress: {
      label: "Zero Trust Adoption",
      value: 86,
      sublabel: "Organization Coverage",
    },
  },
  frameworks: [
    { icon: BadgeCheck, label: "ISO 27001 Certified" },
    { icon: ShieldCheck, label: "NIST 800-63 Compliant" },
    { icon: Activity, label: "NIST CSF Aligned" },
    { icon: Lock, label: "SOC 2 Type II" },
    { icon: ScanFace, label: "DPDP Act Compliant" },
    { icon: Layers, label: "RBI Guidelines Compliant" },
    { icon: Boxes, label: "SEBI Compliant" },
    { icon: ShieldAlert, label: "CIS Controls Aligned" },
  ],
  clusters: [
    {
      index: 1,
      icon: Users,
      title: "Identity Governance & Administration (IGA)",
      description:
        "Automate user lifecycle, access requests, approvals, and reviews with AI-driven governance.",
      href: "/pillars/identity-security-zero-trust/clusters/identity-governance-administration",
    },
    {
      index: 2,
      icon: KeyRound,
      title: "Privileged Access Management (PAM)",
      description: "Discover, monitor, and secure privileged accounts, sessions, and credentials.",
      href: "/pillars/identity-security-zero-trust/clusters/privileged-access-management",
    },
    {
      index: 3,
      icon: Network,
      title: "Zero Trust Network Access (ZTNA)",
      description: "Verify users, devices, and apps continuously. Never trust, always verify.",
      href: "/pillars/identity-security-zero-trust/clusters/zero-trust-network-access",
    },
    {
      index: 4,
      icon: Fingerprint,
      title: "Adaptive Authentication & MFA",
      description: "Risk-based, context-aware authentication with phishing-resistant MFA.",
      href: "/pillars/identity-security-zero-trust/clusters/adaptive-authentication-mfa",
    },
    {
      index: 5,
      icon: Gauge,
      title: "Access Risk & Entitlement Management",
      description: "Identify excessive access, unused permissions, and toxic combinations.",
      href: "/pillars/identity-security-zero-trust/clusters/access-risk-entitlement-management",
    },
    {
      index: 6,
      icon: ShieldAlert,
      title: "Identity Threat Detection & Response",
      description: "Detect impossible travel, credential stuffing, brute force, and insider threats.",
      href: "/pillars/identity-security-zero-trust/clusters/identity-threat-detection-response",
    },
    {
      index: 7,
      icon: Boxes,
      title: "Service Accounts & Secrets Security",
      description: "Discover and secure non-human identities, secrets, API keys, and tokens.",
      href: "/pillars/identity-security-zero-trust/clusters/service-accounts-secrets-security",
    },
    {
      index: 8,
      icon: Layers,
      title: "CIEM & Identity Security Posture",
      description: "Continuously assess identity risks across cloud, SaaS, and on-prem environments.",
      href: "/pillars/identity-security-zero-trust/clusters/ciem-identity-security-posture",
    },
    {
      index: 9,
      icon: ScanFace,
      title: "Microsegmentation & Workload Identity",
      description: "Isolate workloads, enforce least privilege, and secure east-west traffic.",
      href: "/pillars/identity-security-zero-trust/clusters/microsegmentation-workload-identity",
    },
    {
      index: 10,
      icon: BrainCircuit,
      title: "AI-Powered Identity Analytics & UEBA",
      description: "Use AI/ML to detect anomalies, predict risks, and automate identity security.",
      href: "/pillars/identity-security-zero-trust/clusters/ai-identity-analytics-ueba",
    },
  ],
  whyItMatters: [
    {
      icon: ShieldCheck,
      title: "Stop Identity-Based Attacks",
      description: "Block credential abuse and lateral movement.",
    },
    {
      icon: Lock,
      title: "Enforce Least Privilege",
      description: "Give just enough access, for just enough time.",
    },
    {
      icon: ShieldAlert,
      title: "Reduce Breach Impact",
      description: "Contain threats with zero trust segmentation.",
    },
    {
      icon: BadgeCheck,
      title: "Meet Compliance with Confidence",
      description: "Align with DPDP, ISO 27001, RBI, SEBI & more.",
    },
    {
      icon: Gauge,
      title: "Improve Operational Efficiency",
      description: "Automate access reviews and certifications.",
    },
    {
      icon: Users,
      title: "Secure All Identities",
      description: "Users, admins, workloads, and machines.",
    },
  ],
  resources: [
    { icon: Network, title: "Zero Trust Implementation Guide", ctaLabel: "Download Guide", href: "/resources/zero-trust-implementation-guide" },
    { icon: KeyRound, title: "PAM Best Practices", ctaLabel: "Download eBook", href: "/resources/pam-best-practices" },
    { icon: Users, title: "IGA Automation Playbook", ctaLabel: "Download Playbook", href: "/resources/iga-automation-playbook" },
    { icon: Gauge, title: "Identity Security Maturity Model", ctaLabel: "View Model", href: "/resources/identity-security-maturity-model" },
    { icon: BadgeCheck, title: "CIEM Buyer's Guide", ctaLabel: "Download Guide", href: "/resources/ciem-buyers-guide" },
    { icon: ShieldAlert, title: "Identity Threats Report 2024", ctaLabel: "Download Report", href: "/resources/identity-threats-report-2024" },
  ],
  bottomCTA: {
    headline: "Secure Every Identity. Trust Nothing. Verify Everything.",
    description:
      "Strengthen your identity security posture with Cyberteck's AI-native Zero Trust platform.",
    checklist: [
      "Comprehensive Identity Risk Assessment",
      "Zero Trust Readiness Evaluation",
      "Personalized Recommendations",
      "No Obligation. No Credit Card.",
    ],
    primaryCTA: "Get Free Identity Security Assessment",
    secondaryCTA: "Talk to Identity Security Expert",
  },
};
