import {
  ShieldCheck,
  Target,
  Gauge,
  Network,
  ShieldAlert,
  Scale,
  Users,
  Settings,
  Lock,
  BarChart3,
  ClipboardCheck,
  BrainCircuit,
  Activity,
  Layers,
  BadgeCheck,
} from "lucide-react";
import type { Pillar } from "@/lib/types";

export const riskManagement: Pillar = {
  index: 5,
  slug: "risk-management",
  name: "AI-Native Risk Management",
  nameHighlight: "Risk Management",
  clusterSectionLabel: "AI-Native Risk Management",
  clusterSubheading: "Comprehensive risk coverage. Intelligent prioritization. Measurable outcomes.",
  whyMattersLabel: "AI-Native Risk Management",
  resourceSectionLabel: "Risk Management",
  heroPrimaryCTA: "Get Free Risk Assessment",
  tagline: "Identify. Assess. Prioritize. Mitigate. Continuously.",
  description:
    "Cyberteck's AI-powered risk engine continuously discovers assets, identifies risks across people, processes, technology & third parties, quantifies impact, and recommends intelligent mitigations—so you stay ahead of threats and compliance obligations.",
  accentTheme: "violet",
  heroIcon: BrainCircuit,
  featureChips: [
    { icon: Target, label: "Continuous Risk Discovery" },
    { icon: BrainCircuit, label: "AI Risk Scoring" },
    { icon: BarChart3, label: "Business Impact Quantification" },
    { icon: ClipboardCheck, label: "Predictive Analytics" },
  ],
  heroStats: {
    primaryScore: {
      label: "Overall Risk Score",
      value: 78,
      max: 100,
      delta: "High Risk",
      deltaDirection: "up",
      trend: [50, 55, 60, 58, 65, 70, 74, 78],
    },
    supportingStats: [
      {
        label: "Risks Identified",
        value: "2,431",
        delta: "+18.3% vs last month",
        deltaDirection: "up",
        trend: [20, 24, 22, 28, 30, 29, 32, 36],
      },
      {
        label: "Critical Risks",
        value: 243,
        delta: "Requiring Immediate Action",
        deltaDirection: "up",
        trend: [15, 17, 16, 19, 21, 20, 22, 24],
      },
    ],
    donut: {
      label: "Mitigation Status",
      total: "2,431",
      segments: [
        { label: "Mitigated", value: 64, color: "green" },
        { label: "In Progress", value: 24, color: "amber" },
        { label: "Open", value: 12, color: "red" },
      ],
    },
    rankedList: {
      label: "Top Risk Categories",
      items: [
        { label: "Cyber Security", pct: 32 },
        { label: "Third Party", pct: 24 },
        { label: "Compliance", pct: 18 },
        { label: "Operational", pct: 14 },
        { label: "Strategic", pct: 12 },
      ],
    },
    progress: {
      label: "Risk Trend (Last 30 Days)",
      value: 78,
      sublabel: "Overall Risk Score",
    },
  },
  frameworks: [
    { icon: BadgeCheck, label: "ISO 31000 Compliant" },
    { icon: ShieldCheck, label: "NIST RMF Aligned" },
    { icon: Scale, label: "COSO ERM Aligned" },
    { icon: ShieldAlert, label: "RBI Guidelines" },
    { icon: Layers, label: "SEBI Compliant" },
    { icon: Lock, label: "DPDP Act Compliant" },
    { icon: BadgeCheck, label: "ISO 27005 Aligned" },
    { icon: BrainCircuit, label: "AI RMF Ready" },
  ],
  clusters: [
    {
      index: 1,
      icon: Target,
      title: "Enterprise Risk Discovery",
      description: "Continuously discover assets, systems, data flows, and business processes across your enterprise.",
      href: "/pillars/risk-management/clusters/enterprise-risk-discovery",
    },
    {
      index: 2,
      icon: Gauge,
      title: "AI-Powered Risk Assessment",
      description: "AI models analyze threats, vulnerabilities, likelihood, and impact to score risks accurately.",
      href: "/pillars/risk-management/clusters/ai-powered-risk-assessment",
    },
    {
      index: 3,
      icon: Network,
      title: "Risk Prioritization & Ranking",
      description: "Intelligent prioritization based on business impact, likelihood, and risk appetite.",
      href: "/pillars/risk-management/clusters/risk-prioritization-ranking",
    },
    {
      index: 4,
      icon: ShieldCheck,
      title: "Third Party & Supply Chain Risk",
      description: "Monitor and assess vendor, partner, and supply chain risks continuously.",
      href: "/pillars/risk-management/clusters/third-party-supply-chain-risk",
    },
    {
      index: 5,
      icon: Scale,
      title: "Compliance & Regulatory Risk Management",
      description: "Map risks to DPDP, RBI, SEBI, CERT-In, ISO and other regulatory obligations.",
      href: "/pillars/risk-management/clusters/compliance-regulatory-risk-management",
    },
    {
      index: 6,
      icon: Users,
      title: "People & Insider Risk Management",
      description: "Detect insider threats, risky behaviors, and privilege misuse in real-time.",
      href: "/pillars/risk-management/clusters/people-insider-risk-management",
    },
    {
      index: 7,
      icon: Settings,
      title: "Operational Risk Management",
      description: "Identify operational risks across IT, processes, and business functions.",
      href: "/pillars/risk-management/clusters/operational-risk-management",
    },
    {
      index: 8,
      icon: Lock,
      title: "Technology & Cyber Risk Management",
      description: "Assess cyber threats, system vulnerabilities, and tech infrastructure risks.",
      href: "/pillars/risk-management/clusters/technology-cyber-risk-management",
    },
    {
      index: 9,
      icon: BarChart3,
      title: "Risk Analytics & Reporting",
      description: "Real-time dashboards, KRI/KPI tracking, heatmaps, and executive reports.",
      href: "/pillars/risk-management/clusters/risk-analytics-reporting",
    },
    {
      index: 10,
      icon: ClipboardCheck,
      title: "Risk Treatment & Mitigation",
      description: "Automate mitigation plans, track progress, and verify effectiveness.",
      href: "/pillars/risk-management/clusters/risk-treatment-mitigation",
    },
  ],
  whyItMatters: [
    { icon: Target, title: "Proactive Risk Identification", description: "Find risks before they become incidents." },
    { icon: BrainCircuit, title: "Better Decision Making", description: "AI-driven insights for smarter choices." },
    { icon: BadgeCheck, title: "Regulatory Confidence", description: "Stay compliant and audit-ready always." },
    { icon: ShieldCheck, title: "Business Resilience", description: "Reduce disruptions and strengthen resilience." },
    { icon: Gauge, title: "Cost Optimization", description: "Focus on risks that truly matter." },
    { icon: Activity, title: "Continuous Improvement", description: "Learn, adapt, and evolve with AI." },
  ],
  resources: [
    { icon: Target, title: "AI Risk Assessment Framework", ctaLabel: "Download Guide", href: "/resources/ai-risk-assessment-framework" },
    { icon: ClipboardCheck, title: "Risk Register Template", ctaLabel: "Download Template", href: "/resources/risk-register-template" },
    { icon: ShieldCheck, title: "Third Party Risk Assessment Toolkit", ctaLabel: "Download Toolkit", href: "/resources/third-party-risk-assessment-toolkit" },
    { icon: BarChart3, title: "Risk Heatmap Workbook", ctaLabel: "Download Workbook", href: "/resources/risk-heatmap-workbook" },
    { icon: Scale, title: "ISO 31000 Risk Management Guide", ctaLabel: "Download eBook", href: "/resources/iso-31000-risk-management-guide" },
    { icon: Gauge, title: "Risk Dashboard KPIs & Metrics", ctaLabel: "View Dashboard", href: "/resources/risk-dashboard-kpis-metrics" },
  ],
  bottomCTA: {
    headline: "Turn Risk into Resilience. Continuously.",
    description: "Empower your organization with AI-native risk intelligence and build a secure, resilient future.",
    checklist: [
      "AI-Powered Risk Discovery",
      "Real-Time Risk Scoring",
      "Business Impact Quantification",
      "Automated Mitigation Plans",
    ],
    primaryCTA: "Get Free Risk Assessment",
    secondaryCTA: "Talk to a Risk Expert",
  },
};
