import {
  ShieldCheck,
  Zap,
  Network,
  Users,
  BarChart3,
  RefreshCw,
  Bell,
  BrainCircuit,
  Workflow,
  FileSearch,
  Radar,
  ClipboardList,
  Gauge,
  Activity,
  BadgeCheck,
} from "lucide-react";
import type { Pillar } from "@/lib/types";

export const secOpsAutomation: Pillar = {
  index: 9,
  slug: "secops-automation",
  name: "AI Security Operations & Automation",
  nameHighlight: "Operations & Automation",
  clusterSectionLabel: "AI Security Operations & Automation",
  clusterSubheading: "Autonomous SecOps. Intelligent workflows. Continuous response.",
  whyMattersLabel: "AI Security Operations & Automation",
  resourceSectionLabel: "SecOps",
  heroPrimaryCTA: "Request SecOps Demo",
  tagline: "Automate. Orchestrate. Accelerate. Secure at Machine Speed.",
  description:
    "CyberTeck's AI-powered SecOps platform unifies people, processes, and technology to deliver autonomous operations, smarter automation, and faster response—24/7.",
  accentTheme: "blue",
  heroIcon: ShieldCheck,
  featureChips: [
    { icon: Zap, label: "AI-Powered Automation" },
    { icon: Workflow, label: "Orchestration at Scale" },
    { icon: RefreshCw, label: "Real-Time Response" },
    { icon: Users, label: "Human-in-the-Loop Assurance" },
  ],
  heroStats: {
    primaryScore: {
      label: "Open Incidents (24H)",
      value: 326,
      max: 500,
      delta: "-18.7% vs last 24h",
      deltaDirection: "down",
      trend: [420, 400, 390, 370, 360, 345, 335, 326],
    },
    supportingStats: [
      {
        label: "Critical Incidents",
        value: 46,
        delta: "-12.2% vs last 24h",
        deltaDirection: "down",
        trend: [70, 65, 62, 58, 55, 52, 49, 46],
      },
      {
        label: "Entities Monitored",
        value: "2.48M+",
        delta: "+34.9% vs last 30 days",
        deltaDirection: "up",
        trend: [1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4, 2.48],
      },
    ],
    donut: {
      label: "Automation Overview",
      total: "78.4%",
      segments: [
        { label: "Automated", value: 78.4, color: "green" },
        { label: "Assisted", value: 15.6, color: "amber" },
        { label: "Manual", value: 6.0, color: "red" },
      ],
    },
    rankedList: {
      label: "Response Performance",
      items: [
        { label: "Alerts Processed (24H)", pct: 100 },
        { label: "Incidents Responded", pct: 82 },
        { label: "Automation Rate", pct: 78 },
        { label: "MTTR Improvement", pct: 61 },
      ],
    },
    progress: {
      label: "Automation Rate",
      value: 78,
      sublabel: "MTTD 11m 24s · MTTR 28m 19s",
    },
  },
  frameworks: [
    { icon: BadgeCheck, label: "ISO 27001 Certified" },
    { icon: ShieldCheck, label: "SOC 2 CSF Type II" },
    { icon: Radar, label: "MITRE ATT&CK Aligned" },
    { icon: Activity, label: "MEI Cyber Framework" },
    { icon: ShieldCheck, label: "RBI Cyber Framework" },
    { icon: BadgeCheck, label: "DPDP Act Compliant" },
    { icon: Network, label: "CERT-In Ready" },
    { icon: BadgeCheck, label: "GDPR Aligned" },
  ],
  clusters: [
    {
      index: 1,
      icon: Bell,
      title: "Alert Ingestion & Normalization",
      description: "Ingest alerts from all sources, normalize, de-duplicate, and enrich using AI.",
      href: "/pillars/secops-automation/clusters/alert-ingestion-normalization",
    },
    {
      index: 2,
      icon: BrainCircuit,
      title: "AI-Powered Triage & Prioritization",
      description: "Automatically prioritize alerts based on risk, context, and business impact.",
      href: "/pillars/secops-automation/clusters/ai-powered-triage-prioritization",
    },
    {
      index: 3,
      icon: Workflow,
      title: "Automated Incident Response (SOAR)",
      description: "Trigger playbooks, orchestrate actions, and respond in seconds.",
      href: "/pillars/secops-automation/clusters/automated-incident-response-soar",
    },
    {
      index: 4,
      icon: FileSearch,
      title: "Threat Investigation & Enrichment",
      description: "Auto-investigate threats with AI, collect evidence, and enrich context.",
      href: "/pillars/secops-automation/clusters/threat-investigation-enrichment",
    },
    {
      index: 5,
      icon: Radar,
      title: "Threat Detection Engineering",
      description: "Continuously build, tune, and validate detection rules using AI.",
      href: "/pillars/secops-automation/clusters/threat-detection-engineering",
    },
    {
      index: 6,
      icon: ClipboardList,
      title: "Case Management & Collaboration",
      description: "Manage cases, tasks, and collaboration across SecOps teams.",
      href: "/pillars/secops-automation/clusters/case-management-collaboration",
    },
    {
      index: 7,
      icon: BarChart3,
      title: "Threat Intelligence Integration",
      description: "Consume, correlate, and act on global threat intelligence in real time.",
      href: "/pillars/secops-automation/clusters/threat-intelligence-integration",
    },
    {
      index: 8,
      icon: Zap,
      title: "Automation & Orchestration Workflows",
      description: "Design, orchestrate, and scale automated workflows effortlessly.",
      href: "/pillars/secops-automation/clusters/automation-orchestration-workflows",
    },
    {
      index: 9,
      icon: Gauge,
      title: "SecOps Analytics & Reporting",
      description: "Real-time dashboards, KPIs, heatmaps, and executive reports.",
      href: "/pillars/secops-automation/clusters/secops-analytics-reporting",
    },
    {
      index: 10,
      icon: RefreshCw,
      title: "Continuous Improvement & Feedback Loop",
      description: "Learn from every incident, measure performance, and continuously improve.",
      href: "/pillars/secops-automation/clusters/continuous-improvement-feedback-loop",
    },
  ],
  whyItMatters: [
    { icon: Zap, title: "Respond 10X Faster", description: "Automate responses and reduce MTTR drastically." },
    { icon: Workflow, title: "Scale Operations", description: "Handle more alerts, more data, more threats." },
    { icon: Users, title: "Reduce Analyst Fatigue", description: "Eliminate repetitive tasks and focus on what matters." },
    { icon: Gauge, title: "Optimize Costs", description: "Lower operational costs with smart automation." },
    { icon: BrainCircuit, title: "Improve Accuracy", description: "AI reduces human errors and false positives." },
    { icon: BarChart3, title: "Drive Better Outcomes", description: "Consistent, measurable, and continuous improvement." },
  ],
  resources: [
    { icon: Workflow, title: "SOAR Buyer's Guide", ctaLabel: "Download eBook", href: "/resources/soar-buyers-guide" },
    { icon: Zap, title: "SecOps Automation Playbook", ctaLabel: "Download Playbook", href: "/resources/secops-automation-playbook" },
    { icon: ClipboardList, title: "Incident Response Playbook", ctaLabel: "Download Template", href: "/resources/incident-response-playbook" },
    { icon: Gauge, title: "SecOps KPI Dashboard Template", ctaLabel: "Download Template", href: "/resources/secops-kpi-dashboard-template" },
    { icon: Radar, title: "Detection Engineering Guide", ctaLabel: "Download eBook", href: "/resources/detection-engineering-guide" },
    { icon: BadgeCheck, title: "SecOps Maturity Model Assessment", ctaLabel: "Take Assessment", href: "/resources/secops-maturity-model-assessment" },
  ],
  bottomCTA: {
    headline: "Automate Your SecOps. Accelerate Your Defense.",
    description: "Experience the power of AI-driven Security Operations and stay ahead of every threat.",
    checklist: [
      "AI-Powered Automation",
      "Real-Time Orchestration",
      "24/7 Autonomous Operations",
      "No Obligation. No Credit Card.",
    ],
    primaryCTA: "Request SecOps Demo",
    secondaryCTA: "Talk to a SecOps Expert",
  },
};
